robot1:
  controller_manager:
    ros__parameters:

      diffdrive_controller:
        type: diff_drive_controller/DiffDriveController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  diffdrive_controller:
    ros__parameters:
      left_wheel_names: ["left_motor"]
      right_wheel_names: ["right_motor"]

      wheel_separation: 0.48
      wheel_radius: 0.05

      # The real separation between wheels is not resulting in a perfect odometry
      wheel_separation_multiplier: 1.112

      use_stamped_vel: false
      odom_frame_id: "odom"
      base_frame_id: "base_footprint"
      enable_odom_tf: true
      
      linear:
        x:
          max_velocity: 0.1 # Maximal speed of turtlebot
      angular:
        z:
          max_velocity: 0.1  # adjust as needed, units are rad/s

  joint_state_broadcaster:
    ros__parameters:
      extra_joints:
        - LDS-01_secondary_motor
        - LDS-01_main_motor
